### ISSUE TITLE
White screen in Atelier Ryza (first game) on Steam Deck

### ISSUE THREAD

**Issue by Herpderpus666** [doitsujin/atelier-sync-fix#3]
I'm playing Atelier Ryza (first game) on my Steam Deck running the stock image of SteamOS. 
Applying the DLL in the game's files does nothing. I have to set up an override with this launch command: 
WINEDLLOVERRIDES="d3d11=n,b" %command%
As instructed here https://www.protondb.com/app/1121560
If I do this, the game starts but after the logos I see only a white screen, but the game is running, because I can hear the music and sound effects.
I can't try with other Atelier games because I only own Ryza on Steam. I have a PC with a RX6800 and Manjaro Linux, I could try on it but I can't right now, anyway I'd rather play this game on Deck.  

I know the DLL gets loaded with the override command because atfix.log gets created.
This is the content of the log file
Loading d3d11.dll successful, entry points are:
D3D11CreateDevice             @ 0x7ffce7eaf640
D3D11CreateDeviceAndSwapChain @ 0x7ffce7eaf750
Hooking device 0x516480
ID3D11Device::CreateDeferredContext @ 0x7ffce7f14200 -> 0x7ffc9c2b58a0
Hooking context 0x517fd8
ID3D11DeviceContext::ClearRenderTargetView @ 0x7ffce7fb5b50 -> 0x7ffc9c2b2a60
ID3D11DeviceContext::ClearUnorderedAccessViewFloat @ 0x7ffce7fb7d30 -> 0x7ffc9c2b2b10
ID3D11DeviceContext::ClearUnorderedAccessViewUint @ 0x7ffce7fb8f00 -> 0x7ffc9c2b2bc0
ID3D11DeviceContext::CopyResource @ 0x7ffce7fbaf90 -> 0x7ffc9c2b3950
ID3D11DeviceContext::CopySubresourceRegion @ 0x7ffce7fbd930 -> 0x7ffc9c2b3bc0
ID3D11DeviceContext::CopyStructureCount @ 0x7ffce7fbbfb0 -> 0x7ffc9c2b1630
ID3D11DeviceContext::Dispatch @ 0x7ffce7fc3700 -> 0x7ffc9c2b2e50
ID3D11DeviceContext::DispatchIndirect @ 0x7ffce7fc2cd0 -> 0x7ffc9c2b2c70
ID3D11DeviceContext::OMSetRenderTargets @ 0x7ffce7fe22a0 -> 0x7ffc9c2b2d50
ID3D11DeviceContext::OMSetRenderTargetsAndUnorderedAccessViews @ 0x7ffce7fdcc10 -> 0x7ffc9c2b2f30
ID3D11DeviceContext::UpdateSubresource @ 0x7ffce8016bb0 -> 0x7ffc9c2b1490

**Comment by ffrasisti** [comment]
did u use proton ge?

**Comment by Herpderpus666** [comment]
Hi, I fixed it yesterday, I think it was caused by something being wrong on my deck. I was messing with dxvk async and I must have ruined something on my SteamOS install. After reimaging the deck, the game worked just fine with the fix. Btw, you can force 1920x1080 in the game's config file on the wine prefix used by the game, and the game runs at stable 30fps, and looks amazing due to the downscaling from 1080p to the 720p screen :D

Great job on this fix, you should submit it to KT themselves, somehow.
